### ISSUE TITLE
Tag Input State Persistence

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/contexture-react#139]
TagsInput loses it's state between renders, which means that the tag currently being typed resets to empty string. For some reason, inputs are getting rerendered in some of search pages more than they should (likely due to loading indicators we don't really need there), but this also prevents us from implementing the "backspace" functionality to restore a tag. The plan was to wait for react 16.8's hooks to implement functional state, but we might be able to nest components deeper or something to work around it now.

**Comment by doug-patterson** [comment]
@daedalus28 just from looking at it it looks to me that the state object holding the current input needs to be injected into TagsQuery and then pushed down to TagsInput, which could be modified to use a passed in state object when found rather than creating its own on every render. That ought to fix it, but would complicate the relationship between TagsQuery and TagsInput in a way that for all I know is undesired. If that sounds like an OK plan, though, confirm here and I'll give it a shot.

**Comment by daedalus28** [comment]
Even that won't work, because the issue is actually TagsQuery being rerendered, which is likely due to injectTreeNode wrapping it up for loading. The full fix here is probably to make TagsInput a legitimately stateful component using actual react component state, but in the mean time we can (and should) attempt to reduce the amount of rerendering that's happening on the TagsQuery component
