### ISSUE TITLE
The `Date` component should have another name

### ISSUE THREAD

**Issue by sadasant** [smartprocure/contexture-react#35]
The `Date` exampleType component should have another name. Currently, requiring this property alone overwrites the global object Date.

**Comment by daedalus28** [comment]
This is a breaking change, so I'm adding a tag for 2.0 release so we can start to track things we'd want to do in 2.0 (which we should hold for either a lot of little things or at least one major breaking thing that makes the upgrade worthwhile).

**Comment by daedalus28** [comment]
We're preparing 2.0 now and just had a discussion on this. At this point, it is pretty rare for end-users to directly import or use `ExampleTypes` (since most usage would be with higher-order components that iterate over trees - especially since we killed Quick Start for now).

This would also be true for Number and potentially our boolean one, too - so in those case, just import `ExampleTypes` and reference it like `ExampleTypes.Date`
